### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by datalorax** [havishak/dataviz_lab1#13]
Hi everybody, really nice job on this. Below is some feedback.

* After you've merged a branch in, it's safe to delete it. That will help keep your repo clean. It almost never occurs that you need a branch after merging it in and, if you happen to, you can always create a new branch.

* When you investigated the different number of bins for the histogram, you used 2, 5, 10, and then jumped all the way to 50. Both 2 and 10 are really low, and the former will almost always be too low. At the same time, 50 is pretty high, so I would have liked to see more investigation between about 15 and 50.

* I actually don't love the `for` loop approach you've used for the bandwidth of the density plots because they're not being stored. If you wanted to take this approach, I'd suggest modifying your code slightly to do something like the following

```r
bin_width = c(0.5, 5, 8, 50)
plots <- vector("list", length(bin_width))

for (i in seq_along(bin_width)) {
  plots[[i]] <- rstats %>% 
    select(display_text_width) %>% 
    ggplot(aes(x = display_text_width))+
    geom_density(color = "cyan4", fill = "cyan3", bw = bin_width[[i]])+
    theme_minimal()+
    labs(
      x = "Characters in Tweet",
      y = "Density",
      subtitle = paste("binwidth = ", bin_width[[i]])
    )
  print(plots[[i]])
}
```

That will give you the same result that you got previously, but if you want to revisit, say, the bandwidth of 8, you could just run `plot[[3]]` and it would print that plot again. Of course, you could also use `purrr::map()` or `base::lapply()` and then you wouldn't have to pre-allocate the vector.

* On lines 118 and 120, you're using `count()` to count the rows of the dataset. Typically this function is used to count observations in a dataset. For example

```r
rstats %>% 
  count(screen_name)
```

would count the number of times each screen name appears in the dataset. If you are just wanting the know the number of rows in the dataset, I would suggest using `base::nrow()`.

Everything else looks great. Nice work!

**Comment by havishak** [comment]
Thanks for your feedback, Daniel! Sharing a follow-up note:
I overwrote the plot object because it wasn't used later. However, I think it's a good programming practice to save the output. In addition, I also know that for loops are discouraged in programming (perhaps because of the way it handles storage and speed). I wonder if there is a better programming approach to execute the same thing - maybe an in-built function?

**Comment by datalorax** [comment]
Hi Hava - `for` loops actually should not be discouraged. If written incorrectly they can be inefficient, and you have to write a lot of text for a single loop, but there is nothing "wrong" with them. The next course focuses heavily on loops (about half the term) so we will talk about that a lot then. But you should not ever feel bad about writing a `for` loop. It is impressive that you are using them!
